- name: Prepare system
  hosts: rpi

  tasks:
    - name: Remove Packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: absent
      with_items:
        - libreoffice-base-core
        - libreoffice-calc
        - libreoffice-common
        - libreoffice-core
        - libreoffice-draw
        - libreoffice-gnome
        - libreoffice-gtk3
        - libreoffice-impress
        - libreoffice-math
        - libreoffice-style-colibre
        - libreoffice-style-elementary
        - libreoffice-style-yaru
        - libreoffice-uiconfig-calc
        - libreoffice-uiconfig-common
        - libreoffice-uiconfig-draw
        - libreoffice-uiconfig-impress
        - libreoffice-uiconfig-math
        - libreoffice-uiconfig-writer
        - libreoffice-writer
        - thunderbird

    - name: Install Required Packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim
        - flex
        - bison
        - libx11-dev
        - clang
        - libgnutls28-dev
        - libopengl-dev
        - libcups2-dev
        - libsdl2-dev
        - libudev-dev
        - libusb-1.0-0-dev
        - libosmesa6-dev
        - libxcomposite-dev
        - libpcap-dev
        - libsane-dev
        - libv4l-dev
        - libgstreamer1.0-dev
        - libvulkan-dev
        - libkrb5-dev
        - libfontconfig-dev
        - libffms2-dev
        - samba-dev
        - opencl-headers
        - ocl-icd-opencl-dev
        - oss4-dev
        - gettext
        - lld

    - name: Add Dezel User
      become: true
      ansible.builtin.user:
        name: dezel
        shell: /bin/bash
        create_home: true
        groups: sudo
        append: true
        password: "$y$j9T$aQmD3m1Y99kWcQ4slkBYj.$amw1mJl9EhVNb5ziaTI5ue4KcSVjgjZyEYNWgIgYMVC"

    - name: Clone Wine gitlab repo
      ansible.builtin.git:
        repo: https://gitlab.winehq.org/wine/wine.git
        dest: /home/dezel/src/wine
        version: wine-10.1
        clone: true
        update: true
      become: true
      become_user: dezel

    - name: Configure Wine
      ansible.builtin.shell:
        cmd: |
          cd /home/dezel/src/wine
          ./configure --host=aarch64-linux-gnu host_alias=aarch64-linux-gnu --enable-win64
      register: result
      changed_when: result.rc == 0
      become: true
      become_user: dezel

    - name: Debug Configure
      ansible.builtin.debug:
        var: result.stderr

    - name: Make Wine
      community.general.make:
        chdir: /home/dezel/src/wine
      become: true
      become_user: dezel

    - name: Create Applications Directory
      ansible.builtin.file:
        path: '{{ item }}'
        state: directory
        mode: '0755'
      become: true
      become_user: dezel
      loop:
        - /home/dezel/Applications
        - /home/dezel/Applications/LabelReprintingCore
        - /home/dezel/Applications/TEST_ARGOX_LABEL_PRINTING

    - name: Copy Files
      ansible.builtin.copy:
        src: '{{ item.src }}'
        dest: '{{ item.dest }}'
        owner: dezel
        group: dezel
        mode: '0744'
      become: true
      become_user: dezel
      loop:
        - { src: './LabelReprintingCore_arm64.zip', dest: '/tmp/LabelReprintingCore_arm64.zip' }
        - { src: './LabelReprintingCore.desktop', dest: '/home/dezel/Desktop/LabelReprintingCore.desktop' }
        - { src: './TEST_ARGOX_LABEL_PRINTING_arm64.zip', dest: '/tmp/TEST_ARGOX_LABEL_PRINTING_arm64.zip' }
        - { src: ;./TEST_ARGOX_LABEL_PRINTING.desktop, dest: '/home/dezel/Desktop/TEST_ARGOX_LABEL_PRINTING.desktop' }

    - name: Unpack Zip File
      ansible.builtin.unarchive:
        src: /tmp/LabelReprintingCore_arm64.zip
        dest: /home/dezel/Applications/LabelReprintingCore
        remote_src: true
      become: true
      become_user: dezel
      loop:
        - { src: '/tmp/LabelReprintingCore_arm64.zip', dest: '/home/dezel/Applications/LabelReprintingCore' }
        - { src: '/tmp/TEST_ARGOX_LABEL_PRINTING_arm64.zip', dest: '/home/dezel/Applications/TEST_ARGOX_LABEL_PRINTING' }
