- name: Install Raspberry PI Custom OS
  hosts: rpi
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Remove Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - libreoffice-base-core
        - libreoffice-calc
        - libreoffice-common
        - libreoffice-core
        - libreoffice-draw
        - libreoffice-gnome
        - libreoffice-gtk3
        - libreoffice-impress
        - libreoffice-math
        - libreoffice-style-colibre
        - libreoffice-style-elementary
        - libreoffice-style-yaru
        - libreoffice-uiconfig-calc
        - libreoffice-uiconfig-common
        - libreoffice-uiconfig-draw
        - libreoffice-uiconfig-impress
        - libreoffice-uiconfig-math
        - libreoffice-uiconfig-writer
        - libreoffice-writer
        - thunderbird

    - name: Install Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - wine64
