- name: Prepare system
  hosts: rpi
  become: true

  tasks:
    - name: Remove Packages
      ansible.builtin.apt:
        update_cache: true
        name: "{{ item }}"
        state: absent
      with_items:
        - libreoffice-base-core
        - libreoffice-calc
        - libreoffice-common
        - libreoffice-core
        - libreoffice-draw
        - libreoffice-gnome
        - libreoffice-gtk3
        - libreoffice-impress
        - libreoffice-math
        - libreoffice-style-colibre
        - libreoffice-style-elementary
        - libreoffice-style-yaru
        - libreoffice-uiconfig-calc
        - libreoffice-uiconfig-common
        - libreoffice-uiconfig-draw
        - libreoffice-uiconfig-impress
        - libreoffice-uiconfig-math
        - libreoffice-uiconfig-writer
        - libreoffice-writer
        - thunderbird

    - name: Install Required Packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - git
        - vim
        - gcc
        - flex
        - bison

    - name: Clone Wine gitlab repo
      ansible.builtin.git:
        repo: https://gitlab.winehq.org/wine/wine.git
        dest: /home/ansible/src/wine
        version: wine-10.1
        clone: true
        update: true

    - name: Configure Wine
      ansible.builtin.shell:
        cmd: |
          cd /home/ansible/src/wine
          ./configure --host=aarch64-linux-gnu host_alias=aarch64-linux-gnu --enable-win64
